[build]
  command = "CI=false npm run install:all && CI=false npm run build"
  publish = "build"
  base = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
