[build]
builder = "nixpacks"
buildCommand = "npm run install:all && npm run build"

[deploy]
startCommand = "NODE_ENV=production npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 10 
