[build]
builder = "nixpacks"
buildCommand = "npm run install:all && cd foro && npm install axios @types/axios"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 
