[build]
builder = "nixpacks"
buildCommand = "npm run install:all && cd foro && npm install axios @types/axios --save && npm install @types/axios --save-dev"

[deploy]
startCommand = "CI=false npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10 
